pikaraoke/routes/admin.py
import datetime
import os
import subprocess
import sys
import threading
import time

import flask_babel
from flask import (
    Blueprint,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)

from pikaraoke.karaoke import Karaoke
from pikaraoke.lib.current_app import get_admin_password, get_karaoke_instance, is_admin

_ = flask_babel.gettext


admin_bp = Blueprint("admin", __name__)


def delayed_halt(cmd: int, k: Karaoke):
    time.sleep(1.5)
    k.queue_clear()
    k.stop()
    if cmd == 0:
        sys.exit()
    if cmd == 1:
        os.system("shutdown now")
    if cmd == 2:
        os.system("reboot")
    if cmd == 3:
        process = subprocess.Popen(["raspi-config", "--expand-rootfs"])
        process.wait()
        os.system("reboot")


@admin_bp.route("/update_ytdl")
def update_ytdl():
    k = get_karaoke_instance()

    def update_youtube_dl():
        time.sleep(3)
        k.upgrade_youtubedl()

    if is_admin():
        flash(
            # MSG: Message shown after starting the youtube-dl update.
            _("Updating youtube-dl! Should take a minute or two... "),
            "is-warning",
        )
        th = threading.Thread(target=update_youtube_dl)
        th.start()
    else:
        # MSG: Message shown after trying to update youtube-dl without admin permissions.
        flash(_("You don't have permission to update youtube-dl"), "is-danger")
    return redirect(url_for("home.home"))


@admin_bp.route("/refresh")
def refresh():
    k = get_karaoke_instance()
    if is_admin():
        k.get_available_songs()
    else:
        # MSG: Message shown after trying to refresh the song list without admin permissions.
        flash(_("You don't have permission to refresh the song list"), "is-danger")
    return redirect(url_for("files.browse"))


@admin_bp.route("/quit")
def quit():
    k = get_karaoke_instance()
    if is_admin():
        # MSG: Message shown after quitting pikaraoke.
        msg = _("Exiting pikaraoke now!")
        flash(msg, "is-danger")
        k.send_notification(msg, "danger")
        th = threading.Thread(target=delayed_halt, args=[0, k])
        th.start()
    else:
        # MSG: Message shown after trying to quit pikaraoke without admin permissions.
        flash(_("You don't have permission to quit"), "is-danger")
    return redirect(url_for("home.home"))


@admin_bp.route("/shutdown")
def shutdown():
    k = get_karaoke_instance()
    if is_admin():
        # MSG: Message shown after shutting down the system.
        msg = _("Shutting down system now!")
        flash(msg, "is-danger")
        k.send_notification(msg, "danger")
        th = threading.Thread(target=delayed_halt, args=[1, k])
        th.start()
    else:
        # MSG: Message shown after trying to shut down the system without admin permissions.
        flash(_("You don't have permission to shut down"), "is-danger")
    return redirect(url_for("home.home"))


@admin_bp.route("/reboot")
def reboot():
    k = get_karaoke_instance()
    if is_admin():
        # MSG: Message shown after rebooting the system.
        msg = _("Rebooting system now!")
        flash(msg, "is-danger")
        k.send_notification(msg, "danger")
        th = threading.Thread(target=delayed_halt, args=[2, k])
        th.start()
    else:
        # MSG: Message shown after trying to reboot the system without admin permissions.
        flash(_("You don't have permission to Reboot"), "is-danger")
    return redirect(url_for("home.home"))


@admin_bp.route("/expand_fs")
def expand_fs():
    k = get_karaoke_instance()
    if is_admin() and k.is_raspberry_pi:
        # MSG: Message shown after expanding the filesystem.
        flash(_("Expanding filesystem and rebooting system now!"), "is-danger")
        th = threading.Thread(target=delayed_halt, args=[3, k])
        th.start()
    elif not k.is_raspberry_pi:
        # MSG: Message shown after trying to expand the filesystem on a non-raspberry pi device.
        flash(_("Cannot expand fs on non-raspberry pi devices!"), "is-danger")
    else:
        # MSG: Message shown after trying to expand the filesystem without admin permissions
        flash(_("You don't have permission to resize the filesystem"), "is-danger")
    return redirect(url_for("home.home"))


@admin_bp.route("/auth", methods=["POST"])
def auth():
    d = request.form.to_dict()
    admin_password = get_admin_password()
    p = d["admin-password"]
    if p == admin_password:
        resp = make_response(redirect("/"))
        expire_date = datetime.datetime.now()
        expire_date = expire_date + datetime.timedelta(days=90)
        resp.set_cookie("admin", admin_password, expires=expire_date)
        # MSG: Message shown after logging in as admin successfully
        flash(_("Admin mode granted!"), "is-success")
    else:
        resp = make_response(redirect(url_for("login")))
        # MSG: Message shown after failing to login as admin
        flash(_("Incorrect admin password!"), "is-danger")
    return resp


@admin_bp.route("/login")
def login():
    return render_template("login.html")


@admin_bp.route("/logout")
def logout():
    resp = make_response(redirect("/"))
    resp.set_cookie("admin", "")
    # MSG: Message shown after logging out as admin successfully
    flash(_("Logged out of admin mode!"), "is-success")
    return resp

pikaraoke/routes/files.py
import os

import flask_babel
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_paginate import Pagination, get_page_parameter

from pikaraoke.lib.current_app import get_karaoke_instance, get_site_name, is_admin

_ = flask_babel.gettext


files_bp = Blueprint("files", __name__)


@files_bp.route("/browse", methods=["GET"])
def browse():
    k = get_karaoke_instance()
    site_name = get_site_name()
    search = False
    q = request.args.get("q")
    if q:
        search = True
    page = request.args.get(get_page_parameter(), type=int, default=1)

    available_songs = k.available_songs

    letter = request.args.get("letter")

    if letter:
        result = []
        if letter == "numeric":
            for song in available_songs:
                f = k.filename_from_path(song)[0]
                if f.isnumeric():
                    result.append(song)
        else:
            for song in available_songs:
                f = k.filename_from_path(song).lower()
                if f.startswith(letter.lower()):
                    result.append(song)
        available_songs = result

    if "sort" in request.args and request.args["sort"] == "date":
        songs = sorted(available_songs, key=lambda x: os.path.getctime(x))
        songs.reverse()
        sort_order = "Date"
    else:
        songs = available_songs
        sort_order = "Alphabetical"

    results_per_page = 500
    pagination = Pagination(
        css_framework="bulma",
        page=page,
        total=len(songs),
        search=search,
        record_name="songs",
        per_page=results_per_page,
    )
    start_index = (page - 1) * (results_per_page - 1)
    return render_template(
        "files.html",
        pagination=pagination,
        sort_order=sort_order,
        site_title=site_name,
        letter=letter,
        # MSG: Title of the files page.
        title=_("Browse"),
        songs=songs[start_index : start_index + results_per_page],
        admin=is_admin(),
    )


@files_bp.route("/files/delete", methods=["GET"])
def delete_file():
    k = get_karaoke_instance()
    if "song" in request.args:
        song_path = request.args["song"]
        exists = any(item.get("file") == song_path for item in k.queue)
        if exists:
            flash(
                # MSG: Message shown after trying to delete a song that is in the queue.
                _("Error: Can't delete this song because it is in the current queue")
                + ": "
                + song_path,
                "is-danger",
            )
        else:
            k.delete(song_path)
            # MSG: Message shown after deleting a song. Followed by the song path
            flash(_("Song deleted: %s") % k.filename_from_path(song_path), "is-warning")
    else:
        # MSG: Message shown after trying to delete a song without specifying the song.
        flash(_("Error: No song specified!"), "is-danger")
    return redirect(url_for("files.browse"))


@files_bp.route("/files/edit", methods=["GET", "POST"])
def edit_file():
    k = get_karaoke_instance()
    site_name = get_site_name()
    # MSG: Message shown after trying to edit a song that is in the queue.
    queue_error_msg = _("Error: Can't edit this song because it is in the current queue: ")
    if "song" in request.args:
        song_path = request.args["song"]
        # print "SONG_PATH" + song_path
        if song_path in k.queue:
            flash(queue_error_msg + song_path, "is-danger")
            return redirect(url_for("files.browse"))
        else:
            return render_template(
                "edit.html",
                site_title=site_name,
                title="Song File Edit",
                song=song_path.encode("utf-8", "ignore"),
            )
    else:
        d = request.form.to_dict()
        if "new_file_name" in d and "old_file_name" in d:
            new_name = d["new_file_name"]
            old_name = d["old_file_name"]
            if k.is_song_in_queue(old_name):
                # check one more time just in case someone added it during editing
                flash(queue_error_msg + old_name, "is-danger")
            else:
                # check if new_name already exist
                file_extension = os.path.splitext(old_name)[1]
                if os.path.isfile(os.path.join(k.download_path, new_name + file_extension)):
                    flash(
                        # MSG: Message shown after trying to rename a file to a name that already exists.
                        _("Error renaming file: '%s' to '%s', Filename already exists")
                        % (old_name, new_name + file_extension),
                        "is-danger",
                    )
                else:
                    k.rename(old_name, new_name)
                    flash(
                        # MSG: Message shown after renaming a file.
                        _("Renamed file: %s to %s") % (old_name, new_name),
                        "is-warning",
                    )
        else:
            # MSG: Message shown after trying to edit a song without specifying the filename.
            flash(_("Error: No filename parameters were specified!"), "is-danger")
        return redirect(url_for("files.browse"))

pikaraoke/routes/home.py
import flask_babel
from flask import Blueprint, render_template

from pikaraoke.lib.current_app import get_karaoke_instance, get_site_name, is_admin

_ = flask_babel.gettext


home_bp = Blueprint("home", __name__)


@home_bp.route("/")
def home():
    k = get_karaoke_instance()
    site_name = get_site_name()
    return render_template(
        "home.html",
        site_title=site_name,
        title="Home",
        transpose_value=k.now_playing_transpose,
        admin=is_admin(),
        is_transpose_enabled=k.is_transpose_enabled,
    )

pikaraoke/routes/info.py
import flask_babel
import psutil
from flask import Blueprint, render_template

from pikaraoke import VERSION
from pikaraoke.constants import LANGUAGES
from pikaraoke.lib.current_app import (
    get_admin_password,
    get_karaoke_instance,
    get_site_name,
    is_admin,
)
from pikaraoke.lib.get_platform import get_platform

_ = flask_babel.gettext


info_bp = Blueprint("info", __name__)


@info_bp.route("/info")
def info():
    k = get_karaoke_instance()
    site_name = get_site_name()
    url = k.url
    admin_password = get_admin_password()
    is_linux = get_platform() == "linux"

    # 獲取當前偏好語言
    preferred_language = k.get_user_preference("preferred_language", "en")

    # cpu
    try:
        cpu = str(psutil.cpu_percent()) + "%"
    except:
        cpu = _("CPU usage query unsupported")

    # mem
    memory = psutil.virtual_memory()
    available = round(memory.available / 1024.0 / 1024.0, 1)
    total = round(memory.total / 1024.0 / 1024.0, 1)
    memory = (
        str(available) + "MB free / " + str(total) + "MB total ( " + str(memory.percent) + "% )"
    )

    # disk
    disk = psutil.disk_usage("/")
    # Divide from Bytes -> KB -> MB -> GB
    free = round(disk.free / 1024.0 / 1024.0 / 1024.0, 1)
    total = round(disk.total / 1024.0 / 1024.0 / 1024.0, 1)
    disk = str(free) + "GB free / " + str(total) + "GB total ( " + str(disk.percent) + "% )"

    # youtube-dl
    youtubedl_version = k.youtubedl_version

    return render_template(
        "info.html",
        site_title=site_name,
        title="Info",
        url=url,
        admin=is_admin(),
        admin_password=admin_password,
        platform=k.platform,
        os_version=k.os_version,
        ffmpeg_version=k.ffmpeg_version,
        is_transpose_enabled=k.is_transpose_enabled,
        youtubedl_version=youtubedl_version,
        pikaraoke_version=VERSION,
        cpu=cpu,
        memory=memory,
        disk=disk,
        is_linux=is_linux,
        volume=int(k.volume * 100),
        bg_music_volume=int(k.bg_music_volume * 100),
        disable_bg_music=k.disable_bg_music,
        disable_bg_video=k.disable_bg_video,
        disable_score=k.disable_score,
        hide_notifications=k.hide_notifications,
        hide_url=k.hide_url,
        hide_overlay=k.hide_overlay,
        screensaver_timeout=k.screensaver_timeout,
        splash_delay=k.splash_delay,
        normalize_audio=k.normalize_audio,
        cdg_pixel_scaling=k.cdg_pixel_scaling,
        high_quality=k.high_quality,
        complete_transcode_before_play=k.complete_transcode_before_play,
        avsync=k.avsync,
        limit_user_songs_by=k.limit_user_songs_by,
        buffer_size=k.buffer_size,
        languages=LANGUAGES,
        preferred_language=preferred_language,  # 傳遞當前偏好語言
    )

pikaraoke/routes/queue.py
import json

import flask_babel
from flask import Blueprint, flash, redirect, render_template, request, url_for

from pikaraoke.lib.current_app import (
    broadcast_event,
    get_karaoke_instance,
    get_site_name,
    is_admin,
)

try:
    from urllib.parse import unquote
except ImportError:
    from urllib import unquote

_ = flask_babel.gettext

queue_bp = Blueprint("queue", __name__)


@queue_bp.route("/queue")
def queue():
    k = get_karaoke_instance()
    site_name = get_site_name()
    return render_template(
        "queue.html", queue=k.queue, site_title=site_name, title="Queue", admin=is_admin()
    )


@queue_bp.route("/get_queue")
def get_queue():
    k = get_karaoke_instance()
    if len(k.queue) >= 1:
        return json.dumps(k.queue)
    else:
        return json.dumps([])


@queue_bp.route("/queue/addrandom", methods=["GET"])
def add_random():
    k = get_karaoke_instance()
    amount = int(request.args["amount"])
    rc = k.queue_add_random(amount)
    if rc:
        # MSG: Message shown after adding random tracks
        flash(_("Added %s random tracks") % amount, "is-success")
    else:
        # MSG: Message shown after running out songs to add during random track addition
        flash(_("Ran out of songs!"), "is-warning")
    broadcast_event("queue_update")
    return redirect(url_for("queue.queue"))


@queue_bp.route("/queue/edit", methods=["GET"])
def queue_edit():
    k = get_karaoke_instance()
    action = request.args["action"]
    success = False
    if action == "clear":
        k.queue_clear()
        # MSG: Message shown after clearing the queue
        flash(_("Cleared the queue!"), "is-warning")
        broadcast_event("skip", "clear queue")
        success = True
    else:
        song = request.args["song"]
        song = unquote(song)
        if action == "down":
            result = k.queue_edit(song, "down")
            if result:
                # MSG: Message shown after moving a song down in the queue
                flash(_("Moved down in queue") + ": " + song, "is-success")
                success = True
            else:
                # MSG: Message shown after failing to move a song down in the queue
                flash(_("Error moving down in queue") + ": " + song, "is-danger")
        elif action == "up":
            result = k.queue_edit(song, "up")
            if result:
                # MSG: Message shown after moving a song up in the queue
                flash(_("Moved up in queue") + ": " + song, "is-success")
                success = True
            else:
                # MSG: Message shown after failing to move a song up in the queue
                flash(_("Error moving up in queue") + ": " + song, "is-danger")
        elif action == "delete":
            result = k.queue_edit(song, "delete")
            if result:
                # MSG: Message shown after deleting a song from the queue
                flash(_("Deleted from queue") + ": " + song, "is-success")
                success = True
            else:
                # MSG: Message shown after failing to delete a song from the queue
                flash(_("Error deleting from queue") + ": " + song, "is-danger")
    if success:
        broadcast_event("queue_update")
    return redirect(url_for("queue.queue"))


@queue_bp.route("/enqueue", methods=["POST", "GET"])
def enqueue():
    k = get_karaoke_instance()
    if "song" in request.args:
        song = request.args["song"]
    else:
        d = request.form.to_dict()
        song = d["song-to-add"]
    if "user" in request.args:
        user = request.args["user"]
    else:
        d = request.form.to_dict()
        user = d["song-added-by"]
    rc = k.enqueue(song, user)
    broadcast_event("queue_update")
    song_title = k.filename_from_path(song)
    return json.dumps({"song": song_title, "success": rc})

pikaraoke/templates/edit.html
{% extends 'base.html' %}

{% block scripts %}
<script>
  $(function () {

    $('#remove-karaoke').click(function (e) {
      var new_name = clean_title($('#new_file_name').val());
      $('#new_file_name').val(new_name);
    });

    $('#suggest-title').click(function (e) {
      if ($.trim($('#new_file_name').val()) != "") {
        var format_name = clean_title($('#new_file_name').val(), title_case = true);
        var search_string = format_name;
        suggest_title(clean_title(search_string), "#suggest_results");
      }
    });

    $('#swap-order').click(function (e) {
      var split_name = $('#new_file_name').val().split(' - ');
      var new_name = split_name[1] + " - " + split_name[0];
      new_name = new_name.trim();
      $('#new_file_name').val(new_name);
    });
    $('.confirm-delete').click(function (e) {
      e.preventDefault();
      // {# MSG: Confirmation prompt when the user deletes a song. #}
      if (window.confirm("{{ _('Are you sure you want to delete this song from the library?') }}")) {
        location.href = this.href;
      }
    });

    $("#suggest_results").on("click", ".suggested_item", function () {
      $('#new_file_name').val($(this).text());
    });

  });


  function clean_title(search_str, title_case = false) {
    var new_name = $('#new_file_name').val();
    new_name = new_name.replace(/\[+([^\][]+)]+/g, "($1)"); //replace brackets with parenthesis
    new_name = new_name.replace(/[^\x20-\x7E]+/g, "");//Remove all non printable and all non ASCII characters
    new_name = new_name.replace(/\\|\//g, " ");//remove slashes

    //source: https://stackoverflow.com/questions/49655135/javascript-regex-remove-multiple-words-from-string
    var uselessWordsArray =
      [
        "as popularized by", "lyrics", "karafun", "instrumental", "minus one", "minusone", "made famous by", " by ",
        "karaoke version", "karaoke", "hd", "hq", "coversph", "singkaraoke", "in the style of",
        "no lead vocal", "with lyrics", "cc"
      ];
    var expStr = uselessWordsArray.join("|");
    new_name = new_name.replace(new RegExp('\\b(' + expStr + ')\\b', 'gi'), ' ').replace(/\s{2,}/g, ' ');

    if (title_case == true) {
      new_name = new_name.toLowerCase().replace(/\b[a-z]/g, function (letter) {
        return letter.toUpperCase();
      });
    }

    new_name = new_name.replace(/\([\s&\-.)]*\)/g, "");//remove empty parenthesis
    new_name = new_name.replace(/\_/g, '-');//replace _ to dash
    new_name = new_name.replace(/\b\-\b/g, ' - ');//add space before and after dash
    new_name = new_name.replace("&Amp;", "&");
    new_name = new_name.replace(/\&/g, 'and');//replace & to and
    new_name = new_name.replace(/\s\s+/g, " "); //remove white spaces
    return new_name.trim();
  }

  function suggest_title(search_str, results_div, max_suggestion = 5) {
    $('.suggest_loader').removeClass("is-hidden");
    var API_KEY = "058c382f5fd686b4146f6028961c14da";
    var max_suggestion = max_suggestion;
    var url = "https://ws.audioscrobbler.com/2.0/?method=track.search&track=" + search_str + "&limit=" + max_suggestion + "&page=1&api_key=" + API_KEY + "&format=json";
    $(results_div).html("");

    $.getJSON(url, function (json) {
      data = json.results.trackmatches.track;
      suggestions = "";
      if (data.length != 0) {
        $.each(data, function (i, item) {
          suggestions += "<li><a class='suggested_item is-warning'>" + item.name + " - " + item.artist + "</a></li>";
          return i < max_suggestion - 1;
        });
      }
      else {
        // {# MSG: Warning when no suggested tracks are found for a search. #}
        suggestions = "<li>{{ _('No suggestion!') }}</li>";
        console.log("No suggestion!")
      }
      $(results_div).html("<ul>" + suggestions + "</ul>");
    }).always(function () {
      $('.suggest_loader').addClass("is-hidden");
    });
  }


</script>
{% endblock %}

{% block header %}
{# MSG: Page title for the page where a song can be edited. #}
<h1>{% block title %}{% trans %}Edit Song{% endtrans %}{% endblock %}</h1>
{% endblock %}

{% block content %}


<div class="field">
  <form action="{{ url_for('files.edit_file') }}" method="post">
    <div class="field">
      <p class='has-text-warning'>{{ filename_from_path(song.decode('utf-8', 'ignore')) }} </p>
    </div>
    <input value="{{ song.decode('utf-8', 'ignore') }}" type="hidden" name='old_file_name'>
    {# MSG: Label on the control to edit the song's name #}
    <label class="label">{% trans %}Edit Song Name{% endtrans %}</label>
    <div class="field">
      <input autocomplete="off" id="new_file_name" class="input" type="text" name="new_file_name"
        value="{{ filename_from_path(song.decode('utf-8', 'ignore')) }}"></input>
    </div>
    <ul>
      {# MSG: Label on button which auto formats the song's title. #}
      <li><a id='remove-karaoke'>{% trans %}Auto-format{% endtrans %}</a></li>
      {# MSG: Label on button which swaps the order of the artist and song in the title. #}
      <li><a id='swap-order'>{% trans %}Swap artist/song order{% endtrans %}</a></li>
      {# MSG: Label on button which loads results from the website Last.fm and suggests titles based on matches there. #}
      <li><a id='suggest-title'>Suggest from Last.fm</a>
        <span class="button is-loading is-hidden suggest_loader" style="border:0;background-color:transparent;"></span>
        <span id="suggest_results"></span>
      </li>
    </ul>
    <div class="field">
      <button class="button is-primary" id="search-button" type="submit">
        {# MSG: Label on button which saves the changes. #}
        {%- trans %}Save{% endtrans -%}
      </button>
    </div>
  </form>
</div>

<hr>
<a class="edit-button confirm-delete has-text-danger is-pulled-right"
  href="{{url_for('files.delete_file')}}?song={{url_escape(song)}}"><i class="icon icon-trash-empty"></i>
  {# MSG: Label on button which deletes the current song. #}
  {%- trans -%}
    Delete this song
  {%- endtrans -%}
</a><br>

{% endblock %}

pikaraoke/templates/files.html
{% extends 'base.html' %} {% block scripts %}
<script>
  $(function () {
    if ($(window).width() <= 500) {
      $(document).scroll(function () {
        var y = $(this).scrollTop();
        if (y > 100) {
          $("#alpha-bar").removeClass("mobile-hide");
          $("#alpha-bar").fadeIn();
        } else {
          $("#alpha-bar").fadeOut();
        }
      });
    }

    $("a.add-song-link").click(function (e) {
      e.preventDefault();
      setUserCookie();
      var user = Cookies.get("user");
      $.get(this.href + encodeURIComponent(user), function (data) {
        var obj = JSON.parse(data);
        if (obj.success[0]) {
          // {# MSG: Notification when a song gets added to the queue.  The song name comes after this string. #}
          showNotification(obj.success[1], "is-success");
        } else {
          // {# MSG: Notification when a song does not get added to the queue.  The song name comes after this string. #}
          showNotification(obj.success[1], "is-danger");
        }
      });
    });
  });
</script>

{% endblock %} {% block header %}
<h1>
  {% block title %} {% if letter %} {{title}}: "{{ letter.upper() }}" {% else %}
  {{title}} {% endif %} {% endblock %}
</h1>
<style>
  #alpha-bar {
    padding: 5px 10px;
    border-radius: 4px;
    margin-bottom: 10px;
    position: sticky;
    display: flex;
    justify-content: space-between;
    top: 3px;
    z-index: 20;
  }
  table {
    width: 100%;
    table-layout: auto; /* Allows columns to adjust based on content */
  }
  td {
    word-wrap: break-word; /* Ensures long words break to fit within the cell */
  }
  .break-word {
    word-break: break-all; /* Ensures long words break to fit within the cell */
  }

  @media screen and (max-width: 500px) {
    #alpha-bar {
      font-size: 13px;
      position: fixed;
      display: flex;
      align-items: center;
      right: 8px;
      top: 15px;
      flex-direction: column;
      max-width: 22px;
      height: 95vh;
    }
    .mobile-hide {
      visibility: hidden;
    }
  }
</style>
{% endblock %} {% block content %}

<p>
  {% if sort_order == "Alphabetical" %} {# MSG: Label which displays that the
  songs are currently sorted by alphabetical order. #} {% trans %}Sorted
  Alphabetically{% endtrans %} |
  <a href="{{ url_for('files.browse') }}?sort=date">
    {# MSG: Button which changes how the songs are sorted so they become sorted
    by date. #} {% trans %}Sort by Date{% endtrans %}
  </a>
  {% endif %} {% if sort_order == "Date" %} {# MSG: Label which displays that
  the songs are currently sorted by date. #} {% trans %}Sorted by date{%
  endtrans %} |
  <a href="{{ url_for('files.browse') }}">
    {# MSG: Button which changes how the songs are sorted so they become sorted
    by name. #} {% trans %}Sort by Alphabetical{% endtrans %}
  </a>
  {% endif %}
</p>

<div id="alpha-bar" class="has-background-dark mobile-hide">
  <a href="{{ url_for('files.browse') }}?letter=numeric">#</a>
  {% for letter in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
  'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] %}
  <a href="{{ url_for('files.browse') }}?letter={{letter}}"
    >{{letter.upper()}}</a
  >
  {% endfor %}
</div>

{{ pagination.links }} {{ pagination.info }}
<table>
  {% for song in songs %}
  <tr value="{{ song }}">
    <td style="padding: 5px 0px">{{loop.index + pagination.skip}}</td>
    <td id="{{filename_from_path(song)[0].lower()}}" style="padding-right: 0">
      <a
        class="add-song-link has-text-weight-bold has-text-success"
        title="Add '{{filename_from_path(song)}}' to queue"
        href="{{url_for('queue.enqueue')}}?song={{url_escape(song.encode('utf-8','surrogateescape'))}}&user="
        ><i class="icon icon-list-add"></i>
      </a>
    </td>
    <td class="break-word" style="padding-right: 0">
      {{filename_from_path(song)}}
    </td>
    {% if admin %}
    <td style="padding-right: 0">
      <a
        class="edit-button"
        href="{{url_for('files.edit_file')}}?song={{url_escape(song.encode('utf-8','surrogateescape'))}}"
        title="Edit song"
        ><i class="icon icon-edit-1"></i>
      </a>
    </td>
    {% endif %} {% endfor %}
  </tr>
</table>

{{ pagination.links }} {% endblock %}

pikaraoke/templates/login.html
{% extends 'base.html' %}

{% block scripts %}
<script>

  $(function () {



  });

</script>

{% endblock %}

{% block header %}
<h1>{% block title %}
  {# MSG: Title for the log in page for admins. #}
  {% trans %}Login{% endtrans %}
{% endblock %}</h1>
{% endblock %}

{% block content %}

{# MSG: Title fo the form to enter the administrator password. #}
<p>{% trans %}Enter the administrator password{% endtrans %}</p>
<form action="{{ url_for('admin.auth') }}" method="post">

  <div class="field has-addons" style="margin-bottom: 5px ">
    <div class="control" style="width:100%; max-width:350px">
      <input type="password" name="admin-password" class="input" ></input>
    </div>
    <div class="control">
      {# MSG: Text on submit button for the admin login form. #}
      <button class="button is-rounded">{% trans %}Login{% endtrans %}</button>
    </div>
  </div>

</form>

{% endblock %}